server:
  port: 8999

# mq
# publisher-confirm-type - 消息送达交换机确认
# publisher-returns - 消息送达队列确认
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /hello
    publisher-confirm-type: CORRELATED
    publisher-returns: true
